[workspace]
members = ["crates/tari_deploy", "crates/cli"]
resolver = "2"

[workspace.package]
version = "0.8.0"
edition = "2024"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari-cli"
license = "BSD-3-Clause"

[workspace.dependencies]
tari_deploy = { path = "crates/tari_deploy", version = "0.8" }

tokio = { version = "1.41.1", features = ["full"] }
serde = { version = "1.0.215", features = ["derive"] }
thiserror = "2.0.12"
url = { version = "2.5.3", features = ["default", "serde"] }

tari_wallet_daemon_client = { git = "https://github.com/tari-project/tari-ootle.git", tag = "v0.22.0" }
tari_engine = { git = "https://github.com/tari-project/tari-ootle.git", tag = "v0.22.0" }
tari_engine_types = { git = "https://github.com/tari-project/tari-ootle.git", tag = "v0.22.0" }
tari_ootle_common_types = { git = "https://github.com/tari-project/tari-ootle.git", tag = "v0.22.0" }
tari_template_lib = { git = "https://github.com/tari-project/tari-ootle.git", tag = "v0.22.0" }
